name: go-api-rest-ws-prod

services:
  go-api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "${PORT}:5050"
    depends_on:
      users-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:123456@users-db:5432/users_db?sslmode=disable
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped

  users-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: users_db
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
